# Preâmbulo

Imports, funções, downloads e instalação do Pytorch.

In [0]:
# # Reinstalling torch with the right CUDA bindings.
# !pip3 install -U https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
# !pip3 install -U https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

In [0]:
# Basic imports.
import os
import time
import numpy as np
import torch

from torch import nn
from torch import optim

from torch.utils.data import DataLoader
from torch.utils import data
from torch.backends import cudnn

from torchvision import models
from torchvision import datasets
from torchvision import transforms

from skimage import io

from sklearn import metrics

from matplotlib import pyplot as plt

%matplotlib inline

cudnn.benchmark = True

# Sintaxe básica do Pytorch

Assim como o NumPy, o Pytorch é uma biblioteca de processamento vetorial/matricial/tensorial. Operações sobre os tensores do Pytorch possuem sintaxe consideravelmente parecida com operações sobre tensores do NumPy.

## Casting para o dispositivo correto

Como usaremos processamento vetorial principalmente em GPUs para aprendizado profundo, primeiramente é possível verificar se há uma GPU disponível com o trecho de código abaixo, armazenando os tensores nos dispositivos apropriados.

In [3]:
# Checking if GPU/CUDA is available.
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

print(device)

cuda


## Tensores no Pytorch

Criando tensores novos.

In [4]:
tns = torch.tensor([1, 2, 3, 4, 5, 6])
print(tns)

tensor([1, 2, 3, 4, 5, 6])


Reorganizando tensores.

In [5]:
print(tns.view(2, 3))

# Function view() with -1 infers the shape according to the remaining elements.
print(tns.view(3, -1))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


Iniciando tensores vazios

In [6]:
tns_0 = torch.zeros(2, 3)
tns_1 = torch.ones(2, 3)

print(tns_0)
print(tns_1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Iniciando tensores com valores aleatórios.

In [7]:
tns_u = torch.rand(2, 3) # Flat distribution.
print(tns_u)

tns_n = torch.randn(2, 3) # Normal Distribution.
print(tns_n)

tns_perm = torch.randperm(6) # Random permutation of the interval [0, 5].
print(tns_perm)

tensor([[0.6258, 0.7838, 0.8949],
        [0.5151, 0.3810, 0.6624]])
tensor([[ 0.1726, -0.5982, -1.2703],
        [ 0.1179,  0.1978, -1.8261]])
tensor([5, 4, 3, 1, 2, 0])


Operações com tensores.

In [8]:
print(tns_u)
print(tns_n)

tns_sum = tns_u + tns_n
print(tns_sum)

tensor([[0.6258, 0.7838, 0.8949],
        [0.5151, 0.3810, 0.6624]])
tensor([[ 0.1726, -0.5982, -1.2703],
        [ 0.1179,  0.1978, -1.8261]])
tensor([[ 0.7984,  0.1855, -0.3755],
        [ 0.6330,  0.5788, -1.1637]])


Indexação.

In [9]:
print(tns_sum[1, 1]) # Indexing element.
print(tns_sum[0, :]) # Indexing line.
print(tns_sum[:, 1]) # Indexing column.

tensor(0.5788)
tensor([ 0.7984,  0.1855, -0.3755])
tensor([0.1855, 0.5788])


Convertendo de tensores do numpy.

In [10]:
np_arr = np.random.randn(2, 3)
print(np_arr, np_arr.dtype)

torch_tns = torch.from_numpy(np_arr)
print(torch_tns)

[[-1.62456741  1.16154589  0.99453035]
 [-1.214849   -0.69672331 -0.53064492]] float64
tensor([[-1.6246,  1.1615,  0.9945],
        [-1.2148, -0.6967, -0.5306]], dtype=torch.float64)


Concatenando tensores.

In [11]:
print(tns_u)
print(tns_n)

tns_cat = torch.cat((tns_u, tns_n), 0)
print(tns_cat)

tensor([[0.6258, 0.7838, 0.8949],
        [0.5151, 0.3810, 0.6624]])
tensor([[ 0.1726, -0.5982, -1.2703],
        [ 0.1179,  0.1978, -1.8261]])
tensor([[ 0.6258,  0.7838,  0.8949],
        [ 0.5151,  0.3810,  0.6624],
        [ 0.1726, -0.5982, -1.2703],
        [ 0.1179,  0.1978, -1.8261]])


Várias outras operações sobre tensores do Pytorch podem ser vistas nos seguintes tutoriais:
1.   https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/
2.   https://pytorch.org/tutorials/beginner/pytorch_with_examples.html